jenkins-x-platform:
  postinstalljob:
    enabled: true
  PipelineSecrets:
    DockerConfig: |-
      {
          "credHelpers": {
              "gcr.io": "gcloud",
              "us.gcr.io": "gcloud",
              "eu.gcr.io": "gcloud",
              "asia.gcr.io": "gcloud",
              "staging-k8s.gcr.io": "gcloud"
          }
      }
  expose:
    Annotations:
      helm.sh/hook: post-install,post-upgrade
      helm.sh/hook-delete-policy: hook-succeeded
    config:
      domain: 35.240.10.220.nip.io
      exposer: Ingress
      http: "true"
      pathMode: ""
      tlsacme: "false"
  jenkins:
    Servers:
      Global:
        EnvVars:
          TILLER_NAMESPACE: kube-system
